In [39]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [27]:
data = {"age":[25,32,28,40,35,23,45,29],
        "Salary":[40000,60000,50000,80000,65000,35000,90000,48000],
        "Gender":["Male","Female","Male","Female","Male","Female","Male","Female"],
        "Purchased":[0,1,0,1,1,0,1,0]}

In [28]:
df = pd.DataFrame(data)

In [29]:
df.head()

   age  Salary  Gender  Purchased
0   25   40000    Male          0
1   32   60000  Female          1
2   28   50000    Male          0
3   40   80000  Female          1
4   35   65000    Male          1

In [30]:
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

In [31]:
df

   age  Salary  Gender  Purchased
0   25   40000       1          0
1   32   60000       0          1
2   28   50000       1          0
3   40   80000       0          1
4   35   65000       1          1
5   23   35000       0          0
6   45   90000       1          1
7   29   48000       0          0

In [32]:
x = df[["age", "Salary","Gender"]]
y = df["Purchased"]

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [35]:
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [37]:
x_train_scaled

array([[0.  , 0.  , 1.  ],
       [0.2 , 0.16, 0.  ],
       [0.15, 0.2 , 1.  ],
       [0.5 , 0.5 , 1.  ],
       [0.75, 0.8 , 0.  ],
       [1.  , 1.  , 1.  ]])

In [38]:
x_test_scaled

array([[ 0.35,  0.4 ,  0.  ],
       [-0.1 , -0.1 ,  0.  ]])

In [44]:
model = LogisticRegression()
model.fit(x_train_scaled, y_train)
y_pred = model.predict(x_test_scaled)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

Confusion Matrix:
 [[1 0]
 [1 0]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [42]:
print(y_pred)

[0 0]

In [43]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5

In [48]:
new_data = [[30, 70000, 0]]

In [50]:
new_data_scaled = scaler.fit_transform(new_data)

In [51]:
prediction = model.predict(new_data_scaled)
print("Prediction for new data:", prediction)

Prediction for new data: [0]

In [52]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5